# Generated by Django 3.1.2 on 2020-11-07 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Character",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=70)),
                ("birthday", models.DateField(null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Presumed dead", "Presumed dead"),
                            ("Alive", "Alive"),
                            ("Deceased", "Deceased"),
                            ("Unknown", "Unknown"),
                        ],
                        max_length=13,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Occupation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=70)),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="breakingbadapi_task.character",
                    ),
                ),
            ],
        ),
    ]
