# Generated by Django 3.1.2 on 2020-11-07 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("breakingbadapi_task", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="occupation", name="character",),
        migrations.AddField(
            model_name="occupation",
            name="character",
            field=models.ManyToManyField(to="breakingbadapi_task.Character"),
        ),
    ]
