# Generated by Django 3.1.2 on 2020-11-10 07:41

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("breakingbadapi_task", "0002_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="point",
            field=django.contrib.gis.db.models.fields.PointField(
                default=django.contrib.gis.geos.point.Point(0, 0), srid=4326
            ),
        ),
    ]
