# Generated by Django 3.1.2 on 2020-11-10 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("breakingbadapi_task", "0003_auto_20201110_0741"),
    ]

    operations = [
        migrations.RenameField(
            model_name="location",
            old_name="created_at",
            new_name="timestamp",
        ),
    ]
