# Generated by Django 3.1.2 on 2020-11-10 08:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("breakingbadapi_task", "0004_auto_20201110_0755"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="timestamp",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
