version: '3.3'
services:
  db:
    image: "postgis/postgis"
    container_name: breakingbadapi_db
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    volumes:
      - postgres_data:/var/lib/posgresql/data/

  django:
    build:
      context: .
      dockerfile: docker/django/Dockerfile
    command: /start_local.sh
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db

volumes:
  postgres_data:
